export const DEFAULT_THEMES: { name: string; description: string }[] = [
  { name: "Rural Oncology / Rural Health", description: "Rural oncology care delivery and broader rural health access" },
  { name: "Infusion Landscape", description: "Care delivery and infrastructure for infusion services" },
  { name: "Gen-AI Patient Front Door / Follow-Up", description: "Mostly AI voice for patient intake, triage, and follow-up" },
  { name: "Payer Tech - Appeals, Denials & Payment Integrity", description: "Gen-AI for appeals, denials management, and payment integrity" },
  { name: "Gen-AI in RCM", description: "Generative AI applied to revenue cycle management" },
  { name: "Asynchronous Medical Care Platforms", description: "" },
  { name: "ICHRA & Employer-Driven Payer Decisions", description: "Employers driving payer/benefits decisions via ICHRA" },
  { name: "Home Health Tech", description: "" },
  { name: "Pharma Marketing & Sales Enablement", description: "" },
  { name: "AI in Pharma Services", description: "" },
  { name: "Big Tech in Healthcare", description: "" },
  { name: "Specialty Pharmacy", description: "" },
  { name: "Next Generation EMRs", description: "" },
  { name: "Data Infrastructure for Model Development / Data Marketplaces", description: "" },
  { name: "Biobanks", description: "" },
  { name: "What's Next in Clinical Trials?", description: "" },
  { name: "Healthcare Dev Tools", description: "" },
  { name: "What's Next in Surgical?", description: "" },
  { name: "Model Validation & Bias Evaluation", description: "" },
  { name: "Consumer Health Engagement Platforms", description: "Platforms that actually engage patients, e.g. personalized GPT-driven recommendations" },
  { name: "Community Oncology Practice Landscape", description: "" },
  { name: "Tumor Board Landscape", description: "" },
  { name: "Healthcare Cybersecurity", description: "" },
  { name: "Cardiology Care for Cancer Patients", description: "Managing myocarditis and other cardiac events in cancer patients" },
  { name: "Back Office Robotics", description: "" },
  { name: "AI Primary Care", description: "" },
  { name: "New Therapeutics Delivery Enablement", description: "" },
  { name: "Top Quality Business Models in Health Tech / Health AI", description: "Cross-cutting evaluation theme, not sector-specific" },
  { name: "Oncology-Urology Care Coordination & Integration", description: "" },
  { name: "AI-Enabled Clinical Insights on Top of EMR", description: "" },
  { name: "AI Apps", description: "General AI application layer in healthcare" },
  { name: "Clinical Staff Inbox Management", description: "" },
  { name: "AI Scribes for Non-Health-System (SMB)", description: "AI scribes targeting SMB/independent practices rather than large health systems" },
  { name: "AI Orchestration for Small/Mid-Cap Biotech Operations", description: "" },
  { name: "AI Orchestration for Preclinical In Vivo Studies", description: "For biotech companies running preclinical proof-of-concept studies" },
  { name: "Medical Image Storage, Retrieval & Synthetic Data", description: "" },
  { name: "Radiation Oncology Innovation", description: "" },
  { name: "Surgical Oncology Innovation", description: "" },
  { name: "Computer Use Agents for Clinical & Admin Workflows", description: "" },
  { name: "AI Clinical Labor Force", description: "" },
  { name: "Medicaid / FQHCs", description: "" },
  { name: "Evidence Storage & Prep for Foundation Models", description: "Search and preparation of clinical evidence for foundation model training" },
  { name: "Generative UI / Zero-Click", description: "" },
];
