-- Fund profile (singleton row)
insert into fund_profile (id, sector_focus, stages, check_size_min, check_size_max, check_size_flex_note, investment_lens) values (1, 'Oncology-focused healthtech & digital health', 'Seed – Series A (sometimes Series B)', 5, 15, 'can flex up to +5 / down to -2', 'Trace the actual chain of effect: how could this affect a cancer patient — or someone who might eventually become one — either in care delivery or in getting a life-changing drug/therapy to market faster? Think in hops, not just direct oncology products. E.g. routine PCP tools affect screening/early diagnosis timing; specialty pharmacy and prior-auth tools gate access to extremely expensive cancer drugs even though they don''t look oncology-specific on the surface. Score the strength of that chain honestly (direct vs. multi-hop/diffuse) rather than requiring the company to say ''oncology'' anywhere in its pitch.');

-- Themes
insert into themes (name, description) values ('Rural Oncology / Rural Health', 'Rural oncology care delivery and broader rural health access');
insert into themes (name, description) values ('Infusion Landscape', 'Care delivery and infrastructure for infusion services');
insert into themes (name, description) values ('Gen-AI Patient Front Door / Follow-Up', 'Mostly AI voice for patient intake, triage, and follow-up');
insert into themes (name, description) values ('Payer Tech - Appeals, Denials & Payment Integrity', 'Gen-AI for appeals, denials management, and payment integrity');
insert into themes (name, description) values ('Gen-AI in RCM', 'Generative AI applied to revenue cycle management');
insert into themes (name, description) values ('Asynchronous Medical Care Platforms', '');
insert into themes (name, description) values ('ICHRA & Employer-Driven Payer Decisions', 'Employers driving payer/benefits decisions via ICHRA');
insert into themes (name, description) values ('Home Health Tech', '');
insert into themes (name, description) values ('Pharma Marketing & Sales Enablement', '');
insert into themes (name, description) values ('AI in Pharma Services', '');
insert into themes (name, description) values ('Big Tech in Healthcare', '');
insert into themes (name, description) values ('Specialty Pharmacy', '');
insert into themes (name, description) values ('Next Generation EMRs', '');
insert into themes (name, description) values ('Data Infrastructure for Model Development / Data Marketplaces', '');
insert into themes (name, description) values ('Biobanks', '');
insert into themes (name, description) values ('What''s Next in Clinical Trials?', '');
insert into themes (name, description) values ('Healthcare Dev Tools', '');
insert into themes (name, description) values ('What''s Next in Surgical?', '');
insert into themes (name, description) values ('Model Validation & Bias Evaluation', '');
insert into themes (name, description) values ('Consumer Health Engagement Platforms', 'Platforms that actually engage patients, e.g. personalized GPT-driven recommendations');
insert into themes (name, description) values ('Community Oncology Practice Landscape', '');
insert into themes (name, description) values ('Tumor Board Landscape', '');
insert into themes (name, description) values ('Healthcare Cybersecurity', '');
insert into themes (name, description) values ('Cardiology Care for Cancer Patients', 'Managing myocarditis and other cardiac events in cancer patients');
insert into themes (name, description) values ('Back Office Robotics', '');
insert into themes (name, description) values ('AI Primary Care', '');
insert into themes (name, description) values ('New Therapeutics Delivery Enablement', '');
insert into themes (name, description) values ('Top Quality Business Models in Health Tech / Health AI', 'Cross-cutting evaluation theme, not sector-specific');
insert into themes (name, description) values ('Oncology-Urology Care Coordination & Integration', '');
insert into themes (name, description) values ('AI-Enabled Clinical Insights on Top of EMR', '');
insert into themes (name, description) values ('AI Apps', 'General AI application layer in healthcare');
insert into themes (name, description) values ('Clinical Staff Inbox Management', '');
insert into themes (name, description) values ('AI Scribes for Non-Health-System (SMB)', 'AI scribes targeting SMB/independent practices rather than large health systems');
insert into themes (name, description) values ('AI Orchestration for Small/Mid-Cap Biotech Operations', '');
insert into themes (name, description) values ('AI Orchestration for Preclinical In Vivo Studies', 'For biotech companies running preclinical proof-of-concept studies');
insert into themes (name, description) values ('Medical Image Storage, Retrieval & Synthetic Data', '');
insert into themes (name, description) values ('Radiation Oncology Innovation', '');
insert into themes (name, description) values ('Surgical Oncology Innovation', '');
insert into themes (name, description) values ('Computer Use Agents for Clinical & Admin Workflows', '');
insert into themes (name, description) values ('AI Clinical Labor Force', '');
insert into themes (name, description) values ('Medicaid / FQHCs', '');
insert into themes (name, description) values ('Evidence Storage & Prep for Foundation Models', 'Search and preparation of clinical evidence for foundation model training');
insert into themes (name, description) values ('Generative UI / Zero-Click', '');

-- Portfolio companies
insert into portfolio_companies (name, website) values ('Sage Care', 'https://sage.care');
insert into portfolio_companies (name, website) values ('Atropos Health', 'https://atroposhealth.com');
insert into portfolio_companies (name, website) values ('Healthier', 'https://healthier.inc');
insert into portfolio_companies (name, website) values ('Zingage', 'https://zingage.com');
insert into portfolio_companies (name, website) values ('KeyCare', 'https://keycare.org');
insert into portfolio_companies (name, website) values ('Teal Health', 'https://tealhealth.co');
insert into portfolio_companies (name, website) values ('Proximie', 'https://proximie.com');
insert into portfolio_companies (name, website) values ('Ferrum Health', 'https://ferrumhealth.com');
insert into portfolio_companies (name, website) values ('Daymark Health', 'https://daymarkhealth.com');
insert into portfolio_companies (name, website) values ('Turquoise Health', 'https://turquoise.health');
insert into portfolio_companies (name, website) values ('Getlabs', 'https://getlabs.com');
insert into portfolio_companies (name, website) values ('Fourier', 'https://fourierhealth.com');
insert into portfolio_companies (name, website) values ('Maia Oncology', 'https://maiaoncology.com');
insert into portfolio_companies (name, website) values ('Medable', 'https://medable.com');
insert into portfolio_companies (name, website) values ('Paradigm Health', 'https://paradigm.inc');
insert into portfolio_companies (name, website) values ('TrialSpark (dba Formation Bio)', 'https://formation.bio');
insert into portfolio_companies (name, website) values ('Oncology Analytics', 'https://oncologyanalytics.com');
insert into portfolio_companies (name, website) values ('Apricity Health', '');

-- Source links
insert into source_links (name, url, description) values ('Oncology Ventures (Ben Freeberg)', 'https://oncologyventures.substack.com/', 'Written by an early-stage, cancer-focused VC fund — investment theses and deal commentary directly in your space.');
insert into source_links (name, url, description) values ('Second Opinion (Christina Farr)', 'https://secondopinion.substack.com/', 'Bi-weekly on the business of healthcare — funding rounds, product launches, regulatory shifts, care delivery models.');
insert into source_links (name, url, description) values ('Out-Of-Pocket (Nikhil Krishnan)', 'https://www.outofpocket.health/', 'Deep dives on healthcare business models and payer/provider economics — useful for the payer tech, RCM, and PA/denials themes.');
insert into source_links (name, url, description) values ('Rock Health Weekly', 'https://rockhealth.com/insights/', 'Longest-running digital health funding tracker — good for a fast weekly scan of new rounds across all your themes.');
insert into source_links (name, url, description) values ('Vital Signs (Jacob Effron)', 'https://vitalsigns.substack.com/', 'Health tech company and sub-sector breakdowns from a healthcare-focused VC.');
insert into source_links (name, url, description) values ('Fierce Healthcare / Fierce Oncology', 'https://www.fiercehealthcare.com/', 'Trade press with a running fundraising tracker (used as a source for several hits already in this tool) plus a dedicated oncology vertical.');
insert into source_links (name, url, description) values ('STAT News', 'https://www.statnews.com/', 'Biotech/pharma trade journalism — strong for drug approval timelines and clinical trial news relevant to the Drug/Therapy Acceleration lens.');
insert into source_links (name, url, description) values ('NCI SBIR/STTR Awards', 'https://sbir.cancer.gov/', 'Public database of National Cancer Institute small-business grant awardees — literally cancer-specific early research being commercialized, and it''s a public government database (no ToS risk).');

-- Seed hits (theme_id resolved by theme name lookup)
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Prosper AI', 'https://www.getprosper.ai', (select id from themes where name = 'Gen-AI Patient Front Door / Follow-Up'), 'https://www.healthcareittoday.com/2025/10/30/prosper-ai-raises-5m-to-be-the-default-voice-ai-platform-for-healthcares-450b-admin-crisis/', '$5M seed (Emergence Capital, YC, CRV) — voice AI for healthcare front/back-office workflows. Fits check size well. Chain: if deployed by an oncology practice, handles post-chemo symptom-check calls and follow-up scheduling — the calls that get skipped when staff are overloaded. Horizontal product, oncology is one of many possible verticals; worth asking directly whether they have oncology customers.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('VoiceCare AI', '', (select id from themes where name = 'Gen-AI Patient Front Door / Follow-Up'), 'https://www.prnewswire.com/news-releases/agentic-ai-startup-voicecare-ai-completes-successful-funding-round-302488165.html', '$4.54M seed (Caduceus Capital Partners; Mayo Clinic participated) — voice AI agent "Joy" automates payer comms, prior auth, claims. Just under typical check size. Chain: faster prior-auth turnaround directly shortens the wait between an oncology diagnosis/treatment plan and the patient actually starting therapy.', 'New', 'Both');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Anterior', '', (select id from themes where name = 'Payer Tech - Appeals, Denials & Payment Integrity'), 'https://startupintros.com/orgs/anterior', '$63M raised across 3 rounds — automates prior authorization and clinical review tasks for health plans. Verify current round size/stage vs. fund target. Chain: this is the textbook prior-auth/denials case — cancer therapies are among the most expensive and most frequently delayed by PA, so faster/fairer PA has an outsized effect on time-to-treatment for cancer patients specifically.', 'New', 'Both');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Cohere Health', '', (select id from themes where name = 'Payer Tech - Appeals, Denials & Payment Integrity'), 'https://intuitionlabs.ai/articles/cohere-health-ai-prior-authorization', 'More established player in AI-driven prior authorization — useful as a landscape comp rather than a fresh seed target. Same chain as Anterior: PA delay/denial directly gates access to expensive cancer treatment.', 'New', 'Both');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Procode AI', '', (select id from themes where name = 'Gen-AI in RCM'), 'https://www.fiercehealthcare.com/ai-and-machine-learning/armed-funding-and-acquisition-procode-ai-launches-ai-powered-rcm-medical', 'AI-powered RCM for surgical billing in private practice; added $2M ARR in 5 months post-acquisition. Chain: RCM health keeps independent surgical practices (including surgical oncology) financially viable — billing dysfunction is a real driver of community practice closures, which directly reduces local access to cancer surgery.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Freed AI', '', (select id from themes where name = 'AI Scribes for Non-Health-System (SMB)'), 'https://www.commure.com/blog-scribe/scribe-pricing', 'Self-serve AI scribe priced $39-119/provider/month — squarely targets independent/SMB practices. Chain: documentation burden is a leading driver of physician burnout and early retirement/practice closure, especially in independent community oncology and primary care — both of which shape whether cancer patients have a local practice at all.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Axle Health', '', (select id from themes where name = 'Home Health Tech'), 'https://www.prnewswire.com/news-releases/axle-health-secures-10m-in-series-a-financing-to-revolutionize-home-health-operations-302462151.html', '$10M Series A led by F-Prime, with YC, Pear VC, Lightbank — AI logistics/scheduling for in-home clinician visits. 900% FY24 growth, fits check size well. Chain: home infusion and home-based symptom management are a growing cancer-care delivery model; logistics platforms are the enabling infrastructure for that shift. Worth asking directly about oncology/infusion volume.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Kyra Health', '', (select id from themes where name = 'ICHRA & Employer-Driven Payer Decisions'), 'https://www.cbinsights.com/company/kyra-health', 'Founded 2025, early seed stage — ICHRA solution for employers/employees. Very early. Chain: plan design set through ICHRA determines whether someone has a PCP relationship for routine screening (the earlier a cancer is caught, the more treatable it is) and what they pay out-of-pocket for specialty cancer drugs once diagnosed — a real but multi-hop chain.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Knit Health', '', (select id from themes where name = 'Next Generation EMRs'), 'https://www.fiercehealthcare.com/health-tech/fierce-healthcare-fundraising-tracker-26', '$11.6M seed — "Large Clinical Behavior Model" built on Truveta EMR data spanning 130M+ patients across 30 health systems. Fits check size well. Chain: a model trained on this much longitudinal EMR data is plausible infrastructure for risk stratification and earlier cancer-screening triggers inside routine primary-care encounters.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Honey Health', '', (select id from themes where name = 'Next Generation EMRs'), 'https://www.fiercehealthcare.com/health-tech/fierce-healthcare-fundraising-tracker-26', '$7.8M seed — AI agents that log into existing EHRs and autonomously complete full workflows end-to-end. Dual fit with Computer Use Agents theme. Chain: frees clinician time from EHR busywork back into patient-facing time — including the minutes it takes to flag an at-risk patient for screening or follow up on an abnormal result.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Protege Health', '', (select id from themes where name = 'Data Infrastructure for Model Development / Data Marketplaces'), 'https://siliconangle.com/2026/01/08/protege-raises-30m-grow-governed-marketplace-ai-training-data/', '$30M raised — governed marketplace for AI training data. Round size above typical check. Chain: better-governed, more available clinical training data speeds up development of both cancer-detection models and drug-discovery models — ask specifically what share of their data network is oncology/pathology.', 'New', 'Drug/Therapy Acceleration');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Artbio', '', (select id from themes where name = 'Radiation Oncology Innovation'), 'https://www.biopharmadive.com/news/artbio-series-b-radiopharma-prostate-cancer/754232/', '$132M Series B (Sofinnova, B Capital) — radiopharma (radioligand therapy) targeting prostate cancer. Later-stage than the fund''s typical check, but directly on-thesis: new cancer treatment modality (care delivery) and a drug racing toward approval (time-to-market). Best used for market-mapping / finding an earlier-stage comp.', 'New', 'Both');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Previvor Edge', '', (select id from themes where name = 'Community Oncology Practice Landscape'), 'https://medcitynews.com/2025/10/startupdate-new-developments-for-healthcare-startups/', '$3.3M pre-seed (CoFound Partners, Max Ventures) — cancer prevention & early detection. Pre-seed, slightly below typical check size but the most direct fit in this batch: earlier detection directly changes the care-delivery trajectory for cancer patients, one hop.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Excelsior Sciences', '', (select id from themes where name = 'AI Orchestration for Preclinical In Vivo Studies'), 'https://xtalks.com/biotech-funding-2025-tracker-follow-the-latest-raises-rounds-and-rd-momentum-4542/', '$95M total incl. $70M Series A — "smart bloccs" modular chemistry platform machines can run and AI can learn from. Round well above typical check. Chain: faster preclinical iteration shortens the path to IND for any therapeutic program run on the platform, including oncology programs — confirm what share of client pipelines are oncology.', 'New', 'Drug/Therapy Acceleration');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Attuned Intelligence', '', (select id from themes where name = 'Computer Use Agents for Clinical & Admin Workflows'), 'https://www.fiercehealthcare.com/health-tech/fierce-healthcare-fundraising-tracker-26', '$13M (Oct 2025) — hospital call center AI agents. Fits check size range well. Chain: call-center responsiveness affects how fast a patient gets a screening appointment booked or a post-treatment question answered — a real but fairly diffuse, hospital-wide chain rather than cancer-specific.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Affineon Health', '', (select id from themes where name = 'Clinical Staff Inbox Management'), 'https://www.prnewswire.com/news-releases/ai-startup-secures-5m-to-power-physician-productivity-302366467.html', '$5M oversubscribed seed (GPG Ventures, AI Fund) — AI to streamline the physician/provider inbox. Fits check size well. Chain: inbox overload is exactly where a patient-reported concerning symptom (e.g. a new lump, unexplained pain) can sit unread for days — faster triage here has a direct, if unglamorous, effect on time-to-diagnosis.', 'New', 'Direct Cancer Care Delivery');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Iambic', '', (select id from themes where name = 'What''s Next in Clinical Trials?'), 'https://medcitynews.com/2025/11/startup-iambic-raises-100m-for-clinical-trials-of-ai-discovered-cancer-drugs/', '$100M raised — AI-discovered cancer drug entering clinical trials. Directly on-thesis: AI is compressing the drug-discovery-to-trial timeline for a cancer therapeutic. Round size is well above typical check; look for earlier rounds or comparable earlier-stage companies in AI-driven oncology drug discovery.', 'New', 'Drug/Therapy Acceleration');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('House Rx', '', (select id from themes where name = 'Specialty Pharmacy'), 'https://www.prnewswire.com/news-releases/house-rx-raises-55-million-to-scale-in-clinic-specialty-pharmacy-model-302612560.html', '$55M Series B (NEA, Town Hall Ventures) — in-clinic specialty pharmacy model plus AI-enabled pharmacy management. Later-stage than typical check. Chain: this is the specialty-pharmacy example directly — oncology drugs are among the most expensive specialty medications, and in-clinic dispensing plus better pharmacy ops directly affects whether a patient actually starts and stays on therapy. Confirm oncology share of their book.', 'New', 'Both');
insert into hits (company, website, theme_id, source, notes, status, oncology_relevance) values ('Doctor.One', '', (select id from themes where name = 'Asynchronous Medical Care Platforms'), 'https://www.eu-startups.com/2025/09/polish-health-platform-doctor-one-secures-e4-million-to-expand-its-asynchronous-care-model-for-chronic-patients/', '€4M seed — asynchronous chronic-care platform (Poland, expanding to Germany/Spain/UK). Slightly below typical check size; EU-based, confirm US strategy fit. Chain: continuous async contact with a chronic-care provider is exactly the kind of relationship that catches new symptoms early — but the product is generically chronic-care, not cancer-specific, and the chain is the most diffuse in this batch.', 'New', 'Indirect / General Healthtech');
